---
abstract: 'Fully UTF-8 aware File::Find'
author:
  - 'Hayo Baan <info@hayobaan.nl>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::More: '0.96'
  Test::Warn: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Find-utf8
no_index:
  directory:
    - test_files
requires:
  Carp: '0'
  Encode: '0'
  File::Find: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/HayoBaan/File-Find-utf8/issues
  homepage: http://metacpan.org/release/File-Find-utf8/
  repository: git://github.com/HayoBaan/File-Find-utf8.git
version: '0.004'
